version: "3"
services:
  api:
    image: emaxwell14/node-scaffolding:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
      restart_policy:
         condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
